### PR TITLE
Quick copy command.

### PR DESCRIPTION
**Pull request by SENPAY98K**

### CODE REVIEW

**Comment by geobio** [comment]
I like! not the repo owner, but I like the changes!

**Comment by ghost** [comment]
MacOS 15 Sequoia ?

**Comment by eudy97** [comment]
> MacOS 15 Sequoia?

No device comes with sequoia out of the box nor has it as its recovery image.

**Comment by ghost** [comment]
I mean upgrade from Mac OS 14 bypass mdm to  macOS 15 
thank you for yr time

**Comment by eudy97** [comment]
> I mean upgrade from Mac OS 14 bypass mdm to macOS 15 thank you for yr time

You can upgrade to any version of macOS.

You won't be prompted to enroll again unless you reinstall macOS.

**Pull request closed without merging**
